// Generated by tools/gen_clock_assets.py from assets/clock; do not edit.
// The themed clock faces' pixel art (spec 7.1): RGBA sprites named after the face and
// the file (assets/clock/flip/tile.png is kFlipTile), and the orrery's sine table.
#pragma once

#include <cstdint>

namespace p64::widgets::assets {

struct Sprite {
  uint16_t w, h;
  const uint8_t *rgba;  // w*h*4 bytes, row-major
};

extern const Sprite kFlipDigits;  // flip/digits.png, 99x16
extern const Sprite kFlipTile;  // flip/tile.png, 30x34
extern const Sprite kHorizonCloud;  // horizon/cloud.png, 13x5
extern const Sprite kHorizonFarHills;  // horizon/far-hills.png, 64x18
extern const Sprite kHorizonNearHills;  // horizon/near-hills.png, 64x18
extern const Sprite kHorizonSunLow;  // horizon/sun-low.png, 11x11
extern const Sprite kHorizonSun;  // horizon/sun.png, 11x11
extern const Sprite kHorizonTree;  // horizon/tree.png, 5x8
extern const Sprite kHourglassFrame;  // hourglass/frame.png, 26x52
extern const Sprite kHourglassSand;  // hourglass/sand.png, 4x4
extern const Sprite kLedBezel;  // led/bezel.png, 64x64
extern const Sprite kLedColon;  // led/colon.png, 3x19
extern const Sprite kLedDigits;  // led/digits.png, 159x19
extern const Sprite kLedMini;  // led/mini.png, 59x9
extern const Sprite kLedVfdFrame;  // led/vfd-frame.png, 64x64
extern const Sprite kNixieBase;  // nixie/base.png, 64x4
extern const Sprite kNixieDigits;  // nixie/digits.png, 79x11
extern const Sprite kNixieTube;  // nixie/tube.png, 13x38
extern const Sprite kOrreryEarth;  // orrery/earth.png, 5x5
extern const Sprite kOrreryMercury;  // orrery/mercury.png, 3x3
extern const Sprite kOrreryMoon;  // orrery/moon.png, 3x3
extern const Sprite kOrreryPlate;  // orrery/plate.png, 64x64
extern const Sprite kOrrerySun;  // orrery/sun.png, 9x9
extern const Sprite kWordsAlphabet;  // words/alphabet.png, 103x5
extern const Sprite kWordsBezel;  // words/bezel.png, 64x64

constexpr int kSinQ = 14;
// sin(i tenths of a degree) in Q14, i = 0..3599 (cos is 900 further on).
extern const int16_t kSinQ14[3600];

}  // namespace p64::widgets::assets
