// Generated by tools/gen_clock_assets.py from assets/clock; do not edit.
// The themed clock faces' pixel art (spec 7.1): RGBA sprites named after the face and
// the file (assets/clock/flip/tile.png is kFlipTile), and the orrery's sine table.
#pragma once

#include <cstdint>

namespace p64::widgets::assets {

struct Sprite {
  uint16_t w, h;
  const uint8_t *rgba;  // w*h*4 bytes, row-major
};
// A PNG file kept as it is (assets/clock-png), decoded when its face starts.
struct Png {
  const uint8_t *data;
  uint32_t size;
};

extern const Png kAquariumFishAPng;  // aquarium/fish-a.png, 160x17, 2139 bytes
extern const Png kAquariumFishBPng;  // aquarium/fish-b.png, 208x19, 3328 bytes
extern const Png kAquariumFishCPng;  // aquarium/fish-c.png, 112x10, 1582 bytes
extern const Png kAquariumFrontPng;  // aquarium/front.png, 1024x64, 7783 bytes
extern const Png kAquariumLightsPng;  // aquarium/lights.png, 64x64, 145 bytes
extern const Png kAquariumSignPng;  // aquarium/sign.png, 27x10, 241 bytes
extern const Png kAquariumTankPng;  // aquarium/tank.png, 1024x64, 7651 bytes
extern const Png kHorizonRdCloudAPng;  // horizon_rd/cloud-a.png, 14x8, 262 bytes
extern const Png kHorizonRdCloudBPng;  // horizon_rd/cloud-b.png, 18x9, 255 bytes
extern const Png kHorizonRdLakePng;  // horizon_rd/lake.png, 64x38, 195 bytes
extern const Png kHorizonRdLandPng;  // horizon_rd/land.png, 64x38, 2226 bytes
extern const Png kHorizonRdLightsPng;  // horizon_rd/lights.png, 64x38, 118 bytes
extern const Png kHorizonRdMoonPng;  // horizon_rd/moon.png, 12x12, 444 bytes
extern const Png kHorizonRdSunPng;  // horizon_rd/sun.png, 12x12, 362 bytes
extern const Sprite kBracketDial;  // bracket/dial.png, 64x64
extern const Sprite kFlipDigits;  // flip/digits.png, 99x16
extern const Sprite kFlipTile;  // flip/tile.png, 30x34
extern const Sprite kHorizonCloud;  // horizon/cloud.png, 13x5
extern const Sprite kHorizonFarHills;  // horizon/far-hills.png, 64x18
extern const Sprite kHorizonNearHills;  // horizon/near-hills.png, 64x18
extern const Sprite kHorizonSunLow;  // horizon/sun-low.png, 11x11
extern const Sprite kHorizonSun;  // horizon/sun.png, 11x11
extern const Sprite kHorizonTree;  // horizon/tree.png, 5x8
extern const Sprite kHourglassFrame;  // hourglass/frame.png, 26x52
extern const Sprite kHourglassSand;  // hourglass/sand.png, 4x4
extern const Sprite kLedBezel;  // led/bezel.png, 64x64
extern const Sprite kLedColon;  // led/colon.png, 3x19
extern const Sprite kLedDigits;  // led/digits.png, 159x19
extern const Sprite kLedMini;  // led/mini.png, 59x9
extern const Sprite kLedVfdFrame;  // led/vfd-frame.png, 64x64
extern const Sprite kNixieBase;  // nixie/base.png, 64x4
extern const Sprite kNixieDigits;  // nixie/digits.png, 79x11
extern const Sprite kNixieTube;  // nixie/tube.png, 13x38
extern const Sprite kOrreryEarth;  // orrery/earth.png, 5x5
extern const Sprite kOrreryMercury;  // orrery/mercury.png, 3x3
extern const Sprite kOrreryMoon;  // orrery/moon.png, 3x3
extern const Sprite kOrreryPlate;  // orrery/plate.png, 64x64
extern const Sprite kOrrerySun;  // orrery/sun.png, 9x9
extern const Sprite kStationDial;  // station/dial.png, 64x64
extern const Sprite kWordsAlphabet;  // words/alphabet.png, 103x5
extern const Sprite kWordsBezel;  // words/bezel.png, 64x64

constexpr int kSinQ = 14;
// sin(i tenths of a degree) in Q14, i = 0..3599 (cos is 900 further on).
extern const int16_t kSinQ14[3600];

}  // namespace p64::widgets::assets
