idf_component_register(
    SRCS
        "main.cpp"
        "boot_animation.cpp"
        "show.cpp"
        "loader.cpp"
        "status_screens.cpp"
    INCLUDE_DIRS
        "."
    PRIV_REQUIRES
        p64_gfx
        p64_display
        p64_decode
        p64_playback
        p64_storage
        p64_system
        p64_content
        p64_makapix
        p64_widgets
        p64_stream
        p64_net
        p64_web
        json
        esp_timer
        app_update
        esp_app_format
        nvs_flash
)
