// p64 -- the IANA time zone table (generated by tools/gen_tz_table.py): zone name to
// POSIX TZ rule, so the web UI offers names and daylight saving is automatic.
#pragma once

#include <cstddef>
#include <string>

namespace p64::net::tz {

// The POSIX rule for an IANA name, or nullptr when unknown.
const char *posix_for(const std::string &iana_name);
size_t count();
const char *name_at(size_t index);

}  // namespace p64::net::tz
