#!/usr/bin/env python3
r"""Bakes the themed clock faces' pixel-art assets into the firmware (spec 7.1).

    python tools\gen_clock_assets.py        (from firmware/; needs Pillow)

Reads every PNG under assets/clock/<face>/ (drawn by tools/mock_clock_faces.py, editable
by hand) and writes components/p64_widgets/src/clock_assets.hpp and .cpp: one RGBA array
and one `Sprite` per file, named after the face and the file (assets/clock/flip/tile.png
is `kFlipTile`), plus the orrery's sine table (Q14, tenths of a degree), so the faces need
no floating-point trigonometry and the mock's arithmetic is the firmware's. Rerun after
editing or adding a PNG; the output is committed, so the build needs neither Pillow nor
the PNGs (ADR 0008).
"""

import glob
import math
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
FIRMWARE = os.path.abspath(os.path.join(HERE, ".."))
ASSETS = os.path.join(FIRMWARE, "assets", "clock")
OUT_DIR = os.path.join(FIRMWARE, "components", "p64_widgets", "src")
Q = 14


def ident(face, name):
    return "k" + "".join(p.title() for p in (face + "-" + name).replace("_", "-").split("-"))


def main():
    files = sorted(glob.glob(os.path.join(ASSETS, "*", "*.png")))
    if not files:
        sys.exit(f"no assets under {ASSETS}; run tools/mock_clock_faces.py first")
    hpp = ["// Generated by tools/gen_clock_assets.py from assets/clock; do not edit.",
           "// The themed clock faces' pixel art (spec 7.1): RGBA sprites named after the face and",
           "// the file (assets/clock/flip/tile.png is kFlipTile), and the orrery's sine table.",
           "#pragma once", "", "#include <cstdint>", "", "namespace p64::widgets::assets {", "",
           "struct Sprite {", "  uint16_t w, h;", "  const uint8_t *rgba;  // w*h*4 bytes, row-major", "};", ""]
    cpp = ["// Generated by tools/gen_clock_assets.py from assets/clock; do not edit.",
           "#include \"clock_assets.hpp\"", "", "namespace p64::widgets::assets {", "namespace {"]
    sprites = []
    for path in files:
        face = os.path.basename(os.path.dirname(path))
        name = os.path.splitext(os.path.basename(path))[0]
        img = Image.open(path).convert("RGBA")
        data = list(img.getdata())
        sym = ident(face, name)
        cpp.append(f"const uint8_t {sym}_rgba[] = {{")
        for i in range(0, len(data), 16):
            cpp.append("    " + ", ".join(f"{r},{g},{b},{a}" for r, g, b, a in data[i:i + 16]) + ",")
        cpp.append("};")
        sprites.append((sym, img.width, img.height, f"{face}/{name}.png"))
    cpp.append("}  // namespace")
    cpp.append("")
    for sym, w, h, rel in sprites:
        hpp.append(f"extern const Sprite {sym};  // {rel}, {w}x{h}")
        cpp.append(f"const Sprite {sym} = {{{w}, {h}, {sym}_rgba}};")
    # the sine table: sin(i / 10 degrees) in Q14, i = 0..3599; cos(i) = sin(i + 900)
    table = [int(round(math.sin(math.radians(i / 10)) * (1 << Q))) for i in range(3600)]
    hpp += ["", f"constexpr int kSinQ = {Q};", "// sin(i tenths of a degree) in Q14, i = 0..3599 (cos is 900 further on).",
            "extern const int16_t kSinQ14[3600];", "", "}  // namespace p64::widgets::assets", ""]
    cpp.append("")
    cpp.append("const int16_t kSinQ14[3600] = {")
    for i in range(0, 3600, 20):
        cpp.append("    " + ", ".join(str(v) for v in table[i:i + 20]) + ",")
    cpp += ["};", "", "}  // namespace p64::widgets::assets", ""]
    with open(os.path.join(OUT_DIR, "clock_assets.hpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(hpp))
    with open(os.path.join(OUT_DIR, "clock_assets.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(cpp))
    total = sum(w * h * 4 for _s, w, h, _r in sprites)
    print(f"wrote {len(sprites)} sprites ({total} bytes) and the sine table to {OUT_DIR}")


if __name__ == "__main__":
    sys.exit(main())
