#!/usr/bin/env python3
r"""Rasterises the bundled pixel fonts (assets/fonts) into bitmap glyph tables.

    python tools\gen_fonts.py            (from firmware/; needs Pillow, the system Python has it)

Writes components/p64_gfx/src/fonts_data.cpp: one table per font with every printable
ASCII glyph as rows of bits, its advance, and the font's ascent. The TTFs are drawn at
their native pixel size (Capital Hill 6 px, Everyday Typical 7 px), the sizes at which
Pillow renders them without anti-aliasing; anything else would blur a pixel font. The
output is committed, so the firmware build needs neither Pillow nor the TTFs (ADR 0008).
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FIRMWARE = os.path.abspath(os.path.join(HERE, ".."))
FONTS = [
    # (name, file, pixel size, licence line)
    ("capital-hill", "assets/fonts/capital-hill/Capital_Hill.ttf", 6, "Capital Hill by VEXED (v3x3d.itch.io), CC BY 4.0"),
    ("everyday", "assets/fonts/everyday/Everyday_Typical.ttf", 7, "Everyday Typical by VEXED (v3x3d.itch.io), CC BY 4.0"),
]
OUT = os.path.join(FIRMWARE, "components", "p64_gfx", "src", "fonts_data.cpp")
FIRST, LAST = 32, 126


def render_glyph(font, ch, ascent):
    """Returns (advance, bitmap rows as strings of '#'/'.', top offset from the ascent line)."""
    img = Image.new("L", (64, 48), 0)
    d = ImageDraw.Draw(img)
    origin_y = 8  # room above the ascent line for glyphs that overshoot
    d.text((8, origin_y), ch, font=font, fill=255)
    advance = font.getlength(ch)
    px = img.load()
    rows = []
    ys = [y for y in range(48) if any(px[x, y] for x in range(64))]
    xs = [x for x in range(64) if any(px[x, y] for y in range(48))]
    if not ys:
        return int(round(advance)), [], 0, 0
    top, bottom = min(ys), max(ys)
    left, right = min(xs), max(xs)
    for y in range(top, bottom + 1):
        rows.append("".join("#" if px[x, y] >= 128 else "." for x in range(left, right + 1)))
    # glyph offsets relative to the pen position (8, origin_y) and the ascent line
    return int(round(advance)), rows, left - 8, top - origin_y


def main():
    out = []
    out.append("// Generated by tools/gen_fonts.py from assets/fonts; do not edit. See ADR 0008.")
    out.append("#include \"p64/gfx/fonts.hpp\"")
    out.append("")
    out.append("namespace p64::gfx::fonts {")
    out.append("namespace {")
    for name, path, size, licence in FONTS:
        font = ImageFont.truetype(os.path.join(FIRMWARE, path), size)
        ascent, descent = font.getmetrics()
        glyphs = []
        bitmap_bytes = []
        for code in range(FIRST, LAST + 1):
            ch = chr(code)
            advance, rows, x_off, y_off = render_glyph(font, ch, ascent)
            width = len(rows[0]) if rows else 0
            height = len(rows)
            offset = len(bitmap_bytes)
            for row in rows:
                # pack bits, MSB first, ceil(width/8) bytes per row
                bits = [1 if c == "#" else 0 for c in row]
                while len(bits) % 8:
                    bits.append(0)
                for i in range(0, len(bits), 8):
                    byte = 0
                    for b in bits[i:i + 8]:
                        byte = (byte << 1) | b
                    bitmap_bytes.append(byte)
            glyphs.append((code, advance, width, height, x_off, y_off, offset))
        ident = name.replace("-", "_")
        # The line top is where digits and capitals start (taller glyphs such as quotes
        # draw above it); the bottom takes every descender in.
        caps = [y_off for code, _a, width, height, _x, y_off, _o in glyphs if height and (48 <= code <= 57 or 65 <= code <= 90)]
        inked = [(y_off, y_off + height) for _c, _a, width, height, _x, y_off, _o in glyphs if height]
        top = min(caps)
        bottom = max(b for _t, b in inked)
        # The baseline sits `ascent` below Pillow's line top; the digits' cap height is the
        # font's nominal size.
        out.append(f"// {licence}: {size} px, line top {top}, bottom {bottom}, baseline {ascent}")
        out.append(f"const uint8_t k_{ident}_bits[] = {{")
        for i in range(0, len(bitmap_bytes), 24):
            out.append("    " + ", ".join(f"0x{b:02x}" for b in bitmap_bytes[i:i + 24]) + ",")
        out.append("};")
        out.append(f"const Glyph k_{ident}_glyphs[] = {{")
        for code, advance, width, height, x_off, y_off, offset in glyphs:
            out.append(f"    {{{code}, {advance}, {width}, {height}, {x_off}, {y_off}, {offset}}},  // '{chr(code) if code != 92 else 'backslash'}'")
        out.append("};")
        out.append(f"const Font k_{ident} = {{\"{name}\", {size}, {top}, {bottom}, {ascent}, {FIRST}, {LAST}, k_{ident}_glyphs, k_{ident}_bits}};")
        out.append("")
    out.append("}  // namespace")
    out.append("")
    out.append("const Font *const kFonts[] = {" + ", ".join(f"&k_{n.replace('-', '_')}" for n, _, _, _ in FONTS) + "};")
    out.append(f"const size_t kFontCount = {len(FONTS)};")
    out.append("")
    out.append("}  // namespace p64::gfx::fonts")
    out.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote", OUT, "with", len(FONTS), "fonts")


if __name__ == "__main__":
    sys.exit(main())
